directories:
  output: dist-electron
  buildResources: build
appId: com.saintraphael.gestion
productName: Résidence St Raphaël
copyright: Copyright © 2026 Résidence St Raphaël
icon: public/logo.jpeg
files:
  - filter:
      - electron/**/*
      - .next/**/*
      - public/**/*
      - node_modules/**/*
      - package.json
      - next.config.ts
extraResources: []
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/logo.jpeg
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: public/logo.jpeg
  uninstallerIcon: public/logo.jpeg
  installerHeaderIcon: public/logo.jpeg
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Résidence St Raphaël
linux:
  target:
    - AppImage
    - deb
  icon: public/logo.jpeg
  category: Office
mac:
  target:
    - dmg
  icon: public/logo.jpeg
  category: public.app-category.business
electronVersion: 44.4.2
